name: Deploy Frontend to AWS S3 and CloudFront

on:
  push:
    tags:
      - fe-v*

env:
  AWS_REGION: MY_AWS_REGION

permissions:
  contents: read

jobs:
  deploy:
    name: Build & Deploy Frontend
    runs-on: ubuntu-latest
    environment: production
